version: '3'

services:
  # MySQL
  db:
    image: mysql:8.0.28
    container_name: mysql_8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blazor
      MYSQL_USER: docker
      MYSQL_PASSWORD: blazor33252XL
      TZ: 'Asia/Tokyo'
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./docker/db/data:/var/lib/mysql
    - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306

  # phpMyAdmin
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
    - PMA_ARBITRARY=1
    - PMA_HOSTS=mysql_8
    - PMA_USER=root
    - PMA_PASSWORD=root
    ports:
    - 8081:80